
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    stop_grace_period: 3s
    container_name: php
    network_mode: host
    volumes:
      - ./content:/var/www/html/
      - ./content/uploaded:/var/www/html/uploaded

    command: >
      sh -c "composer install && 
      symfony console cache:clear && 
      symfony server:start --no-tls --allow-http --port=8000 --allow-all-ip --listen-ip=0.0.0.0"

    tty: true

  db:
    image: postgres:16

    container_name: postgres_db
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres

    user: "postgres:postgres"

    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    network_mode: host

volumes:
  pgdata: